version: "3"
services:
  database:
    container_name: database-kupipodaryday
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - internal-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-kupipodaryday
    image: backend-kupipodaryday
    restart: always
    env_file:
      - .env
    ports:
      - "4000:3000"
    depends_on:
      - database
    networks:
      - internet
      - internal-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-kupipodaryday
    image: frontend-kupipodaryday
    restart: always
    ports:
      - "8081:80"
    networks:
      - internet

networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge
